In [2]:
from src.main import data 
import pandas as pd

data
df = data.frame
df

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,class
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48785,39,Private,215419,Bachelors,13,Divorced,Prof-specialty,Not-in-family,White,Female,0,0,36,United-States,<=50K
48786,64,NaN,321403,HS-grad,9,Widowed,NaN,Other-relative,Black,Male,0,0,40,United-States,<=50K
48787,38,Private,374983,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,50,United-States,<=50K
48788,44,Private,83891,Bachelors,13,Divorced,Adm-clerical,Own-child,Asian-Pac-Islander,Male,5455,0,40,United-States,<=50K
48789,35,Self-emp-inc,182148,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,60,United-States,>50K

In [3]:
df.info()
df.isna().sum()
df.duplicated().sum()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 48790 entries, 0 to 48789
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             48790 non-null  int64
 1   workclass       45995 non-null  category
 2   fnlwgt          48790 non-null  int64
 3   education       48790 non-null  category
 4   education_num   48790 non-null  int64
 5   marital_status  48790 non-null  category
 6   occupation      45985 non-null  category
 7   relationship    48790 non-null  category
 8   race            48790 non-null  category
 9   sex             48790 non-null  category
 10  capital_gain    48790 non-null  int64
 11  capital_loss    48790 non-null  int64
 12  hours_per_week  48790 non-null  int64
 13  native_country  47934 non-null  category
 14  class           48790 non-null  category
dtypes: category(9), int64(6)
memory usage: 2.7 MB

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week
count,48790.000000,4.879000e+04,48790.000000,48790.000000,48790.000000,48790.000000
mean,38.652798,1.896690e+05,10.078807,1080.217688,87.595573,40.425886
std,13.708493,1.056172e+05,2.570046,7455.905921,403.209129,12.392729
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.175550e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.781385e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.376062e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.490400e+06,16.000000,99999.000000,4356.000000,99.000000

In [44]:
pd.set_option('display.max_rows', 500)
df.sort_values(['education_num'], ascending= True)
print(len(df[df['education_num'] == 1]))
print(len(df[df['education_num'] == 2]))
print(len(df[df['education_num'] == 3]))
print(len(df[df['education_num'] == 4]))
df[df['education_num'] == 3].head(150)

81
245
507
954

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,class
56,46,Private,216666,5th-6th,3,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,Mexico,<=50K
195,23,Private,197387,5th-6th,3,Married-civ-spouse,Transport-moving,Other-relative,White,Male,0,0,40,Mexico,<=50K
317,22,Private,399087,5th-6th,3,Married-civ-spouse,Machine-op-inspct,Other-relative,White,Female,0,0,40,Mexico,<=50K
335,17,Private,270942,5th-6th,3,Never-married,Other-service,Other-relative,White,Male,0,0,48,Mexico,<=50K
381,46,Private,214955,5th-6th,3,Divorced,Craft-repair,Not-in-family,White,Female,0,2339,45,United-States,<=50K
497,23,Private,403107,5th-6th,3,Never-married,Other-service,Own-child,White,Male,0,0,40,El-Salvador,<=50K
511,53,NaN,251804,5th-6th,3,Widowed,NaN,Unmarried,Black,Female,0,0,30,United-States,<=50K
638,47,Self-emp-inc,248145,5th-6th,3,Married-civ-spouse,Transport-moving,Husband,White,Male,0,0,50,Cuba,<=50K
771,37,Private,327323,5th-6th,3,Separated,Farming-fishing,Not-in-family,White,Male,0,0,32,Guatemala,<=50K
874,55,Private,282753,5th-6th,3,Divorced,Other-service,Unmarried,Black,Male,0,0,25,United-States,<=50K
922,42,Private,274198,5th-6th,3,Married-civ-spouse,Machine-op-inspct,Wife,White,Female,0,0,38,Mexico,<=50K
1295,26,Private,280093,5th-6th,3,Married-civ-spouse,Craft-repair,Husband,White,Male,0,1628,50,United-States,<=50K
1307,26,Private,202203,5th-6th,3,Never-married,Adm-clerical,Own-child,White,Female,0,0,40,Mexico,<=50K
1354,58,Private,132606,5th-6th,3,Divorced,Machine-op-inspct,Not-in-family,Black,Male,0,0,40,United-States,<=50K
1544,69,NaN,473040,5th-6th,3,Divorced,NaN,Not-in-family,White,Male,0,0,40,United-States,<=50K
1633,27,Private,127796,5th-6th,3,Never-married,Farming-fishing,Not-in-family,White,Male,0,0,35,Mexico,<=50K
1789,66,Private,142723,5th-6th,3,Married-spouse-absent,Handlers-cleaners,Unmarried,White,Female,0,0,40,Puerto-Rico,<=50K
2124,47,Private,185254,5th-6th,3,Never-married,Priv-house-serv,Own-child,White,Female,0,0,40,El-Salvador,<=50K
2159,47,Self-emp-not-inc,121124,5th-6th,3,Married-civ-spouse,Sales,Husband,White,Male,0,0,55,Italy,>50K
2213,60,NaN,131852,5th-6th,3,Married-civ-spouse,NaN,Husband,White,Male,0,0,30,United-States,>50K
2446,35,Private,63921,5th-6th,3,Married-civ-spouse,Handlers-cleaners,Husband,White,Male,0,0,40,Mexico,<=50K
2502,60,Private,162947,5th-6th,3,Divorced,Machine-op-inspct,Not-in-family,White,Female,0,0,40,Puerto-Rico,<=50K
2616,27,Private,258102,5th-6th,3,Never-married,Transport-moving,Not-in-family,White,Male,0,0,40,Mexico,<=50K
2639,28,Private,128509,5th-6th,3,Never-married,Machine-op-inspct,Not-in-family,White,Female,0,0,40,NaN,<=50K
2667,38,Private,407068,5th-6th,3,Married-civ-spouse,Other-service,Husband,White,Male,0,0,75,Mexico,<=50K
2784,61,Private,43554,5th-6th,3,Never-married,Handlers-cleaners,Not-in-family,Black,Male,0,2339,40,United-States,<=50K
2815,50,Private,237735,5th-6th,3,Married-civ-spouse,Transport-moving,Husband,White,Male,0,0,37,Mexico,<=50K
2876,25,Private,503012,5th-6th,3,Never-married,Craft-repair,Not-in-family,White,Male,0,0,40,Mexico,<=50K
3045,61,Private,123273,5th-6th,3,Divorced,Transport-moving,Not-in-family,White,Male,0,1876,56,United-States,<=50K
3118,19,Private,130431,5th-6th,3,Never-married,Farming-fishing,Not-in-family,White,Male,0,0,36,Mexico,<=50K
3196,20,Private,221955,5th-6th,3,Married-spouse-absent,Farming-fishing,Other-relative,White,Male,0,0,40,Mexico,<=50K
3286,29,Private,457402,5th-6th,3,Never-married,Other-service,Not-in-family,White,Male,0,0,25,Mexico,<=50K
3347,36,Private,252327,5th-6th,3,Married-spouse-absent,Craft-repair,Other-relative,White,Male,0,0,40,Mexico,<=50K
3404,41,Private,243607,5th-6th,3,Married-civ-spouse,Adm-clerical,Husband,White,Male,0,0,40,Mexico,<=50K
3424,37,Private,336598,5th-6th,3,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,36,Mexico,<=50K
3668,45,Private,199590,5th-6th,3,Married-civ-spouse,Transport-moving,Husband,White,Male,0,0,38,Mexico,<=50K
3675,27,Private,150025,5th-6th,3,Never-married,Handlers-cleaners,Other-relative,White,Male,0,0,40,Guatemala,<=50K
3879,43,Private,128212,5th-6th,3,Married-civ-spouse,Machine-op-inspct,Wife,Asian-Pac-Islander,Female,0,0,40,Vietnam,>50K
3931,75,Private,95985,5th-6th,3,Widowed,Other-service,Unmarried,Black,Male,0,0,10,United-States,<=50K
4130,24,Private,238917,5th-6th,3,Never-married,Craft-repair,Unmarried,White,Male,0,0,40,El-Salvador,<=50K
4581,57,Private,188872,5th-6th,3,Divorced,Transport-moving,Unmarried,White,Male,6497,0,40,United-States,<=50K
4830,52,Private,188644,5th-6th,3,Married-spouse-absent,Craft-repair,Other-relative,White,Male,0,0,40,Mexico,<=50K
4994,43,Private,222971,5th-6th,3,Never-married,Machine-op-inspct,Unmarried,White,Female,0,0,40,Mexico,<=50K
5010,38,Self-emp-not-inc,203836,5th-6th,3,Never-married,Transport-moving,Not-in-family,White,Male,0,0,40,United-States,<=50K
5018,22,Private,445758,5th-6th,3,Never-married,Handlers-cleaners,Not-in-family,White,Male,0,0,40,Mexico,<=50K
5180,25,Private,218667,5th-6th,3,Married-civ-spouse,Handlers-cleaners,Own-child,White,Male,0,0,40,United-States,<=50K
5315,37,Private,227128,5th-6th,3,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
5338,74,NaN,204840,5th-6th,3,Married-civ-spouse,NaN,Husband,White,Male,0,0,56,Mexico,<=50K
5363,49,Local-gov,145290,5th-6th,3,Married-civ-spouse,Other-service,Husband,White,Male,0,0,40,United-States,<=50K
5439,46,Private,267107,5th-6th,3,Married-civ-spouse,Craft-repair,Wife,White,Female,0,0,45,Italy,<=50K
5525,37,Private,130277,5th-6th,3,Separated,Other-service,Unmarried,White,Female,0,0,40,United-States,<=50K
5538,50,Private,128378,5th-6th,3,Married-civ-spouse,Handlers-cleaners,Husband,White,Male,0,0,55,NaN,<=50K
5621,41,NaN,230020,5th-6th,3,Married-civ-spouse,NaN,Husband,Other,Male,0,0,40,United-States,<=50K
5634,42,Private,236110,5th-6th,3,Married-spouse-absent,Craft-repair,Not-in-family,White,Male,0,0,40,Puerto-Rico,<=50K
5714,19,Private,274657,5th-6th,3,Never-married,Other-service,Not-in-family,White,Male,0,0,50,Guatemala,<=50K
5969,53,Private,97411,5th-6th,3,Married-civ-spouse,Machine-op-inspct,Husband,Asian-Pac-Islander,Male,0,0,40,Laos,<=50K
5973,62,Private,368476,5th-6th,3,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,24,Mexico,<=50K
6004,33,Private,93206,5th-6th,3,Married-civ-spouse,Farming-fishing,Husband,Asian-Pac-Islander,Male,0,0,40,Philippines,<=50K
6129,22,NaN,291547,5th-6th,3,Married-civ-spouse,NaN,Wife,Other,Female,0,0,40,Mexico,<=50K
6483,53,Self-emp-inc,246562,5th-6th,3,Married-civ-spouse,Sales,Husband,White,Male,0,0,40,Mexico,>50K
6618,26,Private,289980,5th-6th,3,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,30,Mexico,<=50K
7122,32,Private,243988,5th-6th,3,Married-civ-spouse,Other-service,Husband,White,Male,0,0,40,Mexico,<=50K
7436,36,Private,83089,5th-6th,3,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,7298,0,40,Mexico,>50K
7453,23,Private,528616,5th-6th,3,Married-civ-spouse,Other-service,Husband,White,Male,0,0,40,Mexico,<=50K
7513,29,Private,209934,5th-6th,3,Married-civ-spouse,Other-service,Husband,White,Male,0,0,40,Mexico,<=50K
7703,49,Private,168337,5th-6th,3,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
7766,53,Local-gov,188644,5th-6th,3,Married-civ-spouse,Other-service,Husband,White,Male,0,0,40,Mexico,<=50K
8067,57,NaN,300104,5th-6th,3,Married-civ-spouse,NaN,Husband,White,Male,7298,0,84,United-States,>50K
8271,48,Private,273828,5th-6th,3,Never-married,Handlers-cleaners,Not-in-family,White,Male,0,0,40,Mexico,<=50K
8280,43,Private,143582,5th-6th,3,Married-civ-spouse,Machine-op-inspct,Wife,Asian-Pac-Islander,Female,0,2129,72,NaN,<=50K
8285,46,Private,504725,5th-6th,3,Separated,Handlers-cleaners,Not-in-family,White,Male,0,0,50,Mexico,<=50K
8464,25,Private,359985,5th-6th,3,Never-married,Adm-clerical,Not-in-family,White,Female,0,0,33,Mexico,<=50K
8882,21,Private,376929,5th-6th,3,Never-married,Priv-house-serv,Not-in-family,White,Female,0,0,40,Mexico,<=50K
8976,60,Private,296485,5th-6th,3,Married-civ-spouse,Transport-moving,Husband,White,Male,0,0,40,United-States,<=50K
8981,53,Private,194995,5th-6th,3,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,45,Italy,<=50K
8993,20,Private,390817,5th-6th,3,Never-married,Handlers-cleaners,Not-in-family,White,Male,0,0,25,Mexico,<=50K
9044,23,Private,522881,5th-6th,3,Married-civ-spouse,Other-service,Husband,White,Male,0,0,35,Mexico,<=50K
9133,57,Private,303986,5th-6th,3,Never-married,Other-service,Not-in-family,White,Male,0,0,40,Cuba,<=50K
9249,41,Private,289886,5th-6th,3,Married-civ-spouse,Other-service,Husband,Other,Male,0,1579,40,Nicaragua,<=50K
9282,54,Private,197975,5th-6th,3,Married-civ-spouse,Sales,Husband,White,Male,0,0,51,United-States,<=50K
9387,60,Private,135470,5th-6th,3,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,Mexico,<=50K
9443,28,Private,398220,5th-6th,3,Never-married,Craft-repair,Other-relative,White,Male,0,0,40,Mexico,<=50K
9592,58,Local-gov,239405,5th-6th,3,Divorced,Other-service,Other-relative,Black,Female,0,0,40,Haiti,<=50K
9624,41,Private,277192,5th-6th,3,Married-civ-spouse,Farming-fishing,Wife,White,Female,0,0,40,Mexico,<=50K
9642,43,Private,262038,5th-6th,3,Married-spouse-absent,Farming-fishing,Unmarried,White,Male,0,0,35,Mexico,<=50K
9751,44,Self-emp-not-inc,567788,5th-6th,3,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,40,Mexico,<=50K
9782,45,Self-emp-inc,155664,5th-6th,3,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,NaN,>50K
9850,22,Private,213902,5th-6th,3,Never-married,Priv-house-serv,Other-relative,White,Female,0,0,40,El-Salvador,<=50K
10136,77,NaN,152900,5th-6th,3,Married-civ-spouse,NaN,Husband,White,Male,0,0,20,United-States,<=50K
10164,22,Private,205604,5th-6th,3,Never-married,Machine-op-inspct,Not-in-family,White,Male,0,0,30,Mexico,<=50K
10304,45,Private,234652,5th-6th,3,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,Mexico,<=50K
10341,33,Self-emp-not-inc,249249,5th-6th,3,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,50,United-States,>50K
10401,39,Private,299828,5th-6th,3,Separated,Sales,Unmarried,Black,Female,0,0,30,Puerto-Rico,<=50K
10439,20,Private,528616,5th-6th,3,Never-married,Other-service,Other-relative,White,Male,0,0,40,Mexico,<=50K
10496,56,Self-emp-not-inc,162130,5th-6th,3,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,1887,67,United-States,>50K
10514,36,Private,177616,5th-6th,3,Separated,Machine-op-inspct,Not-in-family,White,Female,0,0,40,United-States,<=50K
10661,45,Private,96798,5th-6th,3,Divorced,Transport-moving,Unmarried,White,Male,0,0,40,United-States,<=50K
10750,27,Private,501172,5th-6th,3,Married-civ-spouse,Transport-moving,Husband,White,Male,0,0,40,Mexico,<=50K
10835,27,Private,373499,5th-6th,3,Never-married,Other-service,Not-in-family,White,Male,0,0,60,El-Salvador,<=50K
10902,74,Private,209454,5th-6th,3,Married-civ-spouse,Transport-moving,Husband,Black,Male,0,0,40,United-States,<=50K
10938,53,Private,146378,5th-6th,3,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
11029,33,Private,348618,5th-6th,3,Married-spouse-absent,Transport-moving,Unmarried,Other,Male,0,0,20,El-Salvador,<=50K
11115,36,Private,58602,5th-6th,3,Never-married,Other-service,Not-in-family,White,Male,0,0,35,United-States,<=50K
11337,30,NaN,288419,5th-6th,3,Married-civ-spouse,NaN,Husband,White,Male,0,0,40,Mexico,<=50K
11403,39,Private,248445,5th-6th,3,Married-civ-spouse,Handlers-cleaners,Husband,White,Male,0,0,40,Mexico,<=50K
11436,23,Private,121650,5th-6th,3,Never-married,Handlers-cleaners,Unmarried,White,Male,0,0,30,United-States,<=50K
11475,73,Local-gov,161027,5th-6th,3,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,20,United-States,<=50K
11564,56,Private,301835,5th-6th,3,Separated,Machine-op-inspct,Not-in-family,White,Male,0,0,40,United-States,<=50K
11598,26,Private,158333,5th-6th,3,Never-married,Transport-moving,Not-in-family,White,Male,0,0,40,Columbia,<=50K
11637,40,Private,145439,5th-6th,3,Married-civ-spouse,Other-service,Husband,Other,Male,4064,0,40,Mexico,<=50K
11728,76,NaN,312500,5th-6th,3,Widowed,NaN,Unmarried,White,Female,0,0,40,United-States,<=50K
11901,71,Private,200418,5th-6th,3,Married-civ-spouse,Transport-moving,Husband,White,Male,0,0,40,United-States,<=50K
11933,46,Private,143189,5th-6th,3,Never-married,Machine-op-inspct,Own-child,White,Female,0,0,40,Dominican-Republic,<=50K
11962,55,Private,83401,5th-6th,3,Widowed,Machine-op-inspct,Unmarried,White,Female,0,0,40,United-States,<=50K
12059,49,Private,80914,5th-6th,3,Never-married,Machine-op-inspct,Not-in-family,White,Male,0,0,45,United-States,<=50K
12126,55,NaN,449576,5th-6th,3,Married-civ-spouse,NaN,Husband,White,Male,0,0,48,Mexico,<=50K
12231,42,Private,183319,5th-6th,3,Married-civ-spouse,Other-service,Husband,White,Male,0,0,40,El-Salvador,<=50K
12250,60,Private,122276,5th-6th,3,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,45,Italy,<=50K
12266,53,Private,224894,5th-6th,3,Married-civ-spouse,Priv-house-serv,Wife,Black,Female,0,0,10,Haiti,<=50K
12383,34,Private,684015,5th-6th,3,Never-married,Handlers-cleaners,Own-child,White,Male,0,0,40,El-Salvador,<=50K
12472,57,Private,103403,5th-6th,3,Married-civ-spouse,Transport-moving,Husband,White,Male,0,0,40,United-States,<=50K
12612,49,Private,232586,5th-6th,3,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
12866,32,Private,245487,5th-6th,3,Married-civ-spouse,Machine-op-inspct,Husband,Amer-Indian-Eskimo,Male,0,0,40,Mexico,<=50K
13021,84,NaN,368925,5th-6th,3,Widowed,NaN,Not-in-family,White,Male,0,0,15,United-States,<=50K
13117,27,Private,110622,5th-6th,3,Never-married,Sales,Own-child,Asian-Pac-Islander,Female,0,0,20,Vietnam,<=50K
13137,31,Private,138416,5th-6th,3,Married-civ-spouse,Handlers-cleaners,Husband,White,Male,0,0,56,Mexico,<=50K
13218,28,Private,155621,5th-6th,3,Never-married,Craft-repair,Not-in-family,White,Male,0,0,40,Columbia,<=50K
13281,18,Private,333611,5th-6th,3,Never-married,Other-service,Other-relative,White,Male,0,0,54,Mexico,<=50K
13297,27,NaN,175552,5th-6th,3,Married-civ-spouse,NaN,Wife,White,Female,0,0,40,Mexico,<=50K
13499,51,NaN,157327,5th-6th,3,Married-civ-spouse,NaN,Husband,Black,Male,0,0,8,United-States,<=50K
13689,63,Self-emp-not-inc,217715,5th-6th,3,Never-married,Sales,Not-in-family,White,Female,0,0,3,United-States,<=50K
13812,37,Private,82283,5th-6th,3,Married-civ-spouse,Other-service,Husband,Asian-Pac-Islander,Male,0,0,40,NaN,<=50K
13829,23,Private,109199,5th-6th,3,Married-civ-spouse,Handlers-cleaners,Husband,White,Male,0,0,40,Mexico,<=50K
13845,45,Private,265083,5th-6th,3,Divorced,Priv-house-serv,Unmarried,White,Female,0,0,35,Mexico,<=50K
13951,23,Private,218445,5th-6th,3,Never-married,Priv-house-serv,Unmarried,White,Female,0,0,12,Mexico,<=50K
14083,68,Private,123653,5th-6th,3,Separated,Other-service,Not-in-family,White,Male,0,0,12,Italy,<=50K
14092,59,Private,214052,5th-6th,3,Divorced,Machine-op-inspct,Unmarried,White,Female,0,0,40,United-States,<=50K
14118,41,NaN,339682,5th-6th,3,Married-civ-spouse,NaN,Husband,White,Male,0,0,40,Mexico,<=50K
14246,69,Private,141181,5th-6th,3,Married-civ-spouse,Adm-clerical,Husband,White,Male,1797,0,40,United-States,<=50K
14310,48,Private,315423,5th-6th,3,Married-civ-spouse,Transport-moving,Husband,White,Male,0,0,40,United-States,<=50K
14454,26,Private,350853,5th-6th,3,Never-married,Transport-moving,Not-in-family,White,Male,0,0,40,NaN,<=50K
14480,33,Local-gov,269604,5th-6th,3,Never-married,Other-service,Unmarried,Other,Female,0,0,40,El-Salvador,<=50K
14497,27,Private,283913,5th-6th,3,Never-married,Priv-house-serv,Not-in-family,White,Female,0,0,65,England,<=50K
14540,38,Local-gov,218184,5th-6th,3,Married-civ-spouse,Handlers-cleaners,Other-relative,White,Male,0,0,40,Mexico,<=50K
14577,35,Private,187415,5th-6th,3,Married-civ-spouse,Machine-op-inspct,Husband,Asian-Pac-Islander,Male,0,0,50,NaN,<=50K
14716,60,Private,170310,5th-6th,3,Married-civ-spouse,Transport-moving,Husband,White,Male,0,0,40,United-States,<=50K
14781,30,Private,136651,5th-6th,3,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,Mexico,<=50K
14888,47,Private,274720,5th-6th,3,Married-civ-spouse,Other-service,Husband,Black,Male,0,0,40,Jamaica,<=50K
14890,35,Federal-gov,205584,5th-6th,3,Never-married,Craft-repair,Not-in-family,White,Male,0,0,40,Mexico,<=50K
14904,41,Private,262038,5th-6th,3,Married-spouse-absent,Farming-fishing,Not-in-family,White,Male,0,0,35,Mexico,<=50K

In [11]:
pd.set_option('display.max_rows', 250)

df2 = df[df['marital_status'] == 'Never-married']
df2['relationship'].value_counts()
# correspondance ok entre 'never married' et relationship

df3 = df[df['marital_status'] == 'Married-civ-spouse']
df3['relationship'].value_counts()
df3[(df3['relationship']=='Own-child') | (df3['relationship']=='Other-relative')].head(250)

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,class
33,30,Federal-gov,59951,Some-college,10,Married-civ-spouse,Adm-clerical,Own-child,White,Male,0,0,40,United-States,<=50K
74,79,Private,124744,Some-college,10,Married-civ-spouse,Prof-specialty,Other-relative,White,Male,0,0,20,United-States,<=50K
195,23,Private,197387,5th-6th,3,Married-civ-spouse,Transport-moving,Other-relative,White,Male,0,0,40,Mexico,<=50K
198,35,Private,138992,Masters,14,Married-civ-spouse,Prof-specialty,Other-relative,White,Male,7298,0,40,United-States,>50K
317,22,Private,399087,5th-6th,3,Married-civ-spouse,Machine-op-inspct,Other-relative,White,Female,0,0,40,Mexico,<=50K
881,32,Private,270335,Bachelors,13,Married-civ-spouse,Adm-clerical,Other-relative,White,Male,0,0,40,Philippines,>50K
903,27,NaN,90270,Assoc-acdm,12,Married-civ-spouse,NaN,Own-child,Amer-Indian-Eskimo,Male,0,0,40,United-States,<=50K
1237,41,Self-emp-not-inc,209344,HS-grad,9,Married-civ-spouse,Sales,Other-relative,White,Female,0,0,40,Cuba,<=50K
1755,25,Private,169323,Bachelors,13,Married-civ-spouse,Exec-managerial,Own-child,White,Female,0,0,40,United-States,<=50K
1931,50,NaN,156008,11th,7,Married-civ-spouse,NaN,Own-child,Black,Female,0,0,40,United-States,<=50K
1932,28,Private,162551,7th-8th,4,Married-civ-spouse,Machine-op-inspct,Other-relative,Asian-Pac-Islander,Female,0,0,48,China,<=50K
1933,25,Private,211231,HS-grad,9,Married-civ-spouse,Tech-support,Other-relative,White,Female,0,0,48,United-States,>50K
2034,27,Private,335764,11th,7,Married-civ-spouse,Sales,Own-child,Black,Male,0,0,35,United-States,<=50K
2193,30,Private,488720,9th,5,Married-civ-spouse,Handlers-cleaners,Other-relative,White,Male,0,0,40,Mexico,<=50K
2261,27,Private,408623,Bachelors,13,Married-civ-spouse,Craft-repair,Other-relative,White,Male,0,0,50,United-States,<=50K
2288,34,Private,268051,Some-college,10,Married-civ-spouse,Protective-serv,Other-relative,Black,Female,0,0,25,Haiti,<=50K
2472,30,Private,432565,Assoc-voc,11,Married-civ-spouse,Tech-support,Other-relative,White,Female,0,0,40,Canada,>50K
2706,27,Local-gov,204098,HS-grad,9,Married-civ-spouse,Handlers-cleaners,Other-relative,White,Male,0,0,50,United-States,<=50K
2730,54,Private,96710,HS-grad,9,Married-civ-spouse,Priv-house-serv,Other-relative,Black,Female,0,0,20,United-States,<=50K
3108,28,Private,119545,Some-college,10,Married-civ-spouse,Exec-managerial,Own-child,White,Male,7688,0,50,United-States,>50K
3714,32,Private,353994,Bachelors,13,Married-civ-spouse,Exec-managerial,Other-relative,Asian-Pac-Islander,Female,0,0,40,China,>50K
3816,29,Local-gov,175262,Masters,14,Married-civ-spouse,Prof-specialty,Other-relative,White,Male,0,0,35,United-States,<=50K
4160,37,Private,195148,HS-grad,9,Married-civ-spouse,Craft-repair,Own-child,White,Male,3137,0,40,United-States,<=50K
4256,20,Private,217421,HS-grad,9,Married-civ-spouse,Adm-clerical,Other-relative,White,Female,0,0,40,United-States,<=50K
4512,29,Private,193260,Bachelors,13,Married-civ-spouse,Craft-repair,Other-relative,Asian-Pac-Islander,Male,0,0,30,India,<=50K
4938,28,State-gov,286310,HS-grad,9,Married-civ-spouse,Adm-clerical,Own-child,White,Female,0,0,40,United-States,<=50K
5066,18,Private,78045,11th,7,Married-civ-spouse,Handlers-cleaners,Own-child,White,Male,0,0,40,United-States,<=50K
5174,25,Private,159662,HS-grad,9,Married-civ-spouse,Sales,Own-child,White,Male,0,0,26,United-States,>50K
5180,25,Private,218667,5th-6th,3,Married-civ-spouse,Handlers-cleaners,Own-child,White,Male,0,0,40,United-States,<=50K
5408,21,Private,146499,Assoc-voc,11,Married-civ-spouse,Adm-clerical,Other-relative,White,Female,0,1579,40,United-States,<=50K
5609,47,Private,176319,HS-grad,9,Married-civ-spouse,Sales,Own-child,White,Female,0,0,38,United-States,>50K
5627,46,Private,199316,Some-college,10,Married-civ-spouse,Craft-repair,Other-relative,Asian-Pac-Islander,Male,0,0,40,India,<=50K
5729,47,Self-emp-not-inc,118506,Bachelors,13,Married-civ-spouse,Exec-managerial,Own-child,White,Male,0,0,60,United-States,<=50K
5897,23,Private,200089,Some-college,10,Married-civ-spouse,Craft-repair,Other-relative,White,Male,0,0,40,El-Salvador,<=50K
6117,58,Private,175127,12th,8,Married-civ-spouse,Transport-moving,Other-relative,White,Male,0,0,40,United-States,<=50K
6267,24,Private,86745,Bachelors,13,Married-civ-spouse,Prof-specialty,Other-relative,Asian-Pac-Islander,Female,0,0,40,Philippines,<=50K
6431,27,Private,211032,Preschool,1,Married-civ-spouse,Farming-fishing,Other-relative,White,Male,41310,0,24,Mexico,<=50K
6568,28,Self-emp-not-inc,123983,Some-college,10,Married-civ-spouse,Sales,Own-child,Asian-Pac-Islander,Male,0,0,63,South,<=50K
6850,32,Private,604506,HS-grad,9,Married-civ-spouse,Transport-moving,Own-child,White,Male,0,0,72,Mexico,<=50K
7123,54,Self-emp-not-inc,82551,Assoc-voc,11,Married-civ-spouse,Tech-support,Other-relative,White,Female,0,0,10,United-States,<=50K
7135,39,Private,143445,HS-grad,9,Married-civ-spouse,Other-service,Other-relative,Black,Female,0,0,40,United-States,<=50K
7307,38,Private,33975,HS-grad,9,Married-civ-spouse,Exec-managerial,Other-relative,White,Male,0,0,40,United-States,>50K
7545,20,Private,141481,11th,7,Married-civ-spouse,Sales,Other-relative,White,Female,0,0,50,United-States,<=50K
7596,46,Private,428350,HS-grad,9,Married-civ-spouse,Other-service,Own-child,White,Female,0,0,15,United-States,<=50K
7598,25,Private,112847,HS-grad,9,Married-civ-spouse,Transport-moving,Own-child,Other,Male,0,0,40,United-States,<=50K
7709,42,Self-emp-not-inc,93099,Some-college,10,Married-civ-spouse,Prof-specialty,Own-child,White,Female,0,0,25,United-States,<=50K
7734,35,Private,242094,HS-grad,9,Married-civ-spouse,Other-service,Other-relative,Black,Male,0,0,40,United-States,<=50K
7789,19,Private,165310,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Other-relative,White,Male,0,0,20,United-States,<=50K
8016,30,Private,177522,HS-grad,9,Married-civ-spouse,Adm-clerical,Own-child,White,Female,0,0,20,United-States,<=50K
8144,23,Private,222925,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Own-child,White,Female,2105,0,40,United-States,<=50K
8196,39,Federal-gov,200968,Some-college,10,Married-civ-spouse,Adm-clerical,Other-relative,White,Male,0,0,45,United-States,>50K
8412,45,Private,81132,Some-college,10,Married-civ-spouse,Craft-repair,Other-relative,Asian-Pac-Islander,Male,0,0,40,Philippines,<=50K
8671,28,NaN,168524,Assoc-voc,11,Married-civ-spouse,NaN,Own-child,White,Female,0,0,40,United-States,<=50K
9065,48,Private,162096,9th,5,Married-civ-spouse,Machine-op-inspct,Other-relative,Asian-Pac-Islander,Female,0,0,45,China,<=50K
9112,40,Private,224658,Some-college,10,Married-civ-spouse,Sales,Other-relative,White,Male,0,0,40,United-States,<=50K
9208,33,NaN,193172,Assoc-voc,11,Married-civ-spouse,NaN,Own-child,White,Female,7688,0,50,United-States,>50K
9741,32,Private,236543,12th,8,Married-civ-spouse,Craft-repair,Other-relative,White,Male,0,0,40,Mexico,<=50K
9840,25,Private,395512,12th,8,Married-civ-spouse,Machine-op-inspct,Other-relative,Other,Male,0,0,40,Mexico,<=50K
9979,33,Private,409172,Bachelors,13,Married-civ-spouse,Exec-managerial,Own-child,White,Male,0,0,55,United-States,<=50K
10005,53,Private,46155,HS-grad,9,Married-civ-spouse,Priv-house-serv,Other-relative,White,Female,0,0,40,United-States,<=50K
10114,20,NaN,173945,11th,7,Married-civ-spouse,NaN,Other-relative,White,Female,0,0,39,United-States,<=50K
10229,21,NaN,207988,HS-grad,9,Married-civ-spouse,NaN,Other-relative,White,Female,0,0,35,United-States,<=50K
10273,55,Private,202559,Bachelors,13,Married-civ-spouse,Other-service,Other-relative,Asian-Pac-Islander,Male,0,0,35,Philippines,<=50K
10275,32,Private,153326,Bachelors,13,Married-civ-spouse,Prof-specialty,Other-relative,White,Male,0,0,40,United-States,<=50K
10366,38,Private,133586,HS-grad,9,Married-civ-spouse,Protective-serv,Own-child,White,Male,0,0,45,United-States,<=50K
10563,38,Private,136137,Some-college,10,Married-civ-spouse,Exec-managerial,Other-relative,White,Male,0,0,50,United-States,>50K
10593,49,State-gov,31650,Bachelors,13,Married-civ-spouse,Prof-specialty,Other-relative,White,Female,0,0,45,United-States,<=50K
10707,25,Private,190350,10th,6,Married-civ-spouse,Other-service,Own-child,White,Female,0,0,35,United-States,<=50K
10848,22,Private,43646,HS-grad,9,Married-civ-spouse,Craft-repair,Own-child,White,Male,0,0,40,United-States,<=50K
10889,20,Private,146706,Some-college,10,Married-civ-spouse,Sales,Other-relative,White,Female,0,0,30,United-States,<=50K
11046,55,Private,381965,Bachelors,13,Married-civ-spouse,Craft-repair,Other-relative,White,Male,0,0,40,United-States,<=50K
11159,33,Private,167939,HS-grad,9,Married-civ-spouse,Other-service,Own-child,White,Female,0,0,25,United-States,<=50K
11185,50,Private,135643,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Other-relative,Asian-Pac-Islander,Female,0,0,40,China,<=50K
11610,59,Private,268840,Some-college,10,Married-civ-spouse,Adm-clerical,Other-relative,White,Female,0,0,16,United-States,>50K
12065,20,Private,291979,HS-grad,9,Married-civ-spouse,Sales,Other-relative,White,Male,0,0,20,United-States,<=50K
12097,27,Private,214858,10th,6,Married-civ-spouse,Craft-repair,Other-relative,White,Male,0,0,55,United-States,<=50K
12169,55,Local-gov,99131,HS-grad,9,Married-civ-spouse,Prof-specialty,Other-relative,White,Female,0,2246,40,United-States,>50K
12315,29,Private,203697,Bachelors,13,Married-civ-spouse,Prof-specialty,Own-child,White,Male,0,0,75,United-States,<=50K
12516,22,Private,243923,HS-grad,9,Married-civ-spouse,Transport-moving,Other-relative,White,Male,0,0,80,United-States,<=50K
12771,28,Private,48894,HS-grad,9,Married-civ-spouse,Adm-clerical,Own-child,White,Female,0,0,40,United-States,<=50K
12805,44,Private,279183,Some-college,10,Married-civ-spouse,Other-service,Own-child,White,Female,0,0,40,United-States,>50K
12825,29,Private,138332,Some-college,10,Married-civ-spouse,Adm-clerical,Own-child,White,Female,0,0,6,United-States,<=50K
12843,21,Private,548303,HS-grad,9,Married-civ-spouse,Prof-specialty,Own-child,White,Male,0,0,40,Mexico,>50K
12858,37,Private,219546,Bachelors,13,Married-civ-spouse,Exec-managerial,Other-relative,White,Male,3411,0,47,United-States,<=50K
12989,28,Private,66777,Assoc-voc,11,Married-civ-spouse,Other-service,Other-relative,White,Female,3137,0,40,United-States,<=50K
13110,43,Private,168412,HS-grad,9,Married-civ-spouse,Sales,Other-relative,White,Female,0,0,44,Poland,<=50K
13969,36,Local-gov,177858,Bachelors,13,Married-civ-spouse,Prof-specialty,Own-child,White,Male,0,0,40,United-States,<=50K
13985,20,Private,109952,HS-grad,9,Married-civ-spouse,Tech-support,Other-relative,White,Male,0,0,40,United-States,<=50K
14322,75,Private,191446,1st-4th,2,Married-civ-spouse,Other-service,Other-relative,Black,Female,0,0,16,United-States,<=50K
14398,40,Private,365986,Bachelors,13,Married-civ-spouse,Handlers-cleaners,Own-child,White,Male,0,0,40,United-States,>50K
14540,38,Local-gov,218184,5th-6th,3,Married-civ-spouse,Handlers-cleaners,Other-relative,White,Male,0,0,40,Mexico,<=50K
14550,19,Self-emp-not-inc,342384,11th,7,Married-civ-spouse,Craft-repair,Own-child,White,Male,0,2129,55,United-States,<=50K
14636,22,Private,110371,HS-grad,9,Married-civ-spouse,Other-service,Own-child,White,Male,0,0,50,United-States,<=50K
14757,30,Private,72887,HS-grad,9,Married-civ-spouse,Craft-repair,Own-child,Asian-Pac-Islander,Male,3411,0,40,United-States,<=50K
14774,39,State-gov,221059,Masters,14,Married-civ-spouse,Prof-specialty,Other-relative,Other,Female,7688,0,38,United-States,>50K
14908,61,Private,339358,5th-6th,3,Married-civ-spouse,Farming-fishing,Other-relative,White,Female,0,0,45,Mexico,<=50K
15035,25,State-gov,156848,HS-grad,9,Married-civ-spouse,Protective-serv,Own-child,White,Male,0,0,35,United-States,<=50K
15191,42,Private,143582,7th-8th,4,Married-civ-spouse,Other-service,Other-relative,Asian-Pac-Islander,Female,0,0,48,NaN,<=50K
15357,32,Private,106541,5th-6th,3,Married-civ-spouse,Other-service,Other-relative,White,Male,0,0,40,United-States,<=50K
15438,20,Private,219266,HS-grad,9,Married-civ-spouse,Prof-specialty,Own-child,White,Female,0,0,36,NaN,<=50K
15814,22,Private,31387,Bachelors,13,Married-civ-spouse,Adm-clerical,Own-child,Amer-Indian-Eskimo,Female,2885,0,25,United-States,<=50K
15861,40,State-gov,150533,Bachelors,13,Married-civ-spouse,Prof-specialty,Other-relative,White,Male,0,0,40,United-States,<=50K
16134,34,Private,188736,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Other-relative,Other,Female,0,0,20,Columbia,<=50K
16152,34,Private,123084,11th,7,Married-civ-spouse,Machine-op-inspct,Own-child,White,Female,0,0,40,United-States,<=50K
17213,39,Private,100669,Some-college,10,Married-civ-spouse,Craft-repair,Own-child,Asian-Pac-Islander,Male,0,0,40,United-States,<=50K
17255,28,Private,67218,7th-8th,4,Married-civ-spouse,Sales,Other-relative,White,Male,0,0,40,United-States,<=50K
17383,22,Private,390817,5th-6th,3,Married-civ-spouse,Craft-repair,Other-relative,White,Male,0,0,40,Mexico,<=50K
17420,23,Private,201664,HS-grad,9,Married-civ-spouse,Adm-clerical,Other-relative,White,Male,0,0,40,United-States,<=50K
17438,44,Private,317535,1st-4th,2,Married-civ-spouse,Protective-serv,Other-relative,White,Male,0,0,40,Mexico,<=50K
17503,36,Private,186808,Bachelors,13,Married-civ-spouse,Craft-repair,Own-child,White,Male,0,0,40,United-States,>50K
17700,58,Private,223400,Assoc-acdm,12,Married-civ-spouse,Priv-house-serv,Other-relative,White,Female,0,0,35,Poland,<=50K
17719,28,Private,158737,12th,8,Married-civ-spouse,Machine-op-inspct,Other-relative,Other,Male,0,0,40,Ecuador,<=50K
17870,55,Private,240988,9th,5,Married-civ-spouse,Machine-op-inspct,Other-relative,Asian-Pac-Islander,Male,0,0,40,Philippines,<=50K
18161,49,Private,323773,11th,7,Married-civ-spouse,Priv-house-serv,Other-relative,White,Female,0,0,40,United-States,<=50K
18333,53,Private,158352,5th-6th,3,Married-civ-spouse,Other-service,Other-relative,White,Female,0,0,24,Italy,<=50K
18455,42,Private,367533,10th,6,Married-civ-spouse,Craft-repair,Own-child,Other,Male,0,0,43,United-States,>50K
18570,30,Private,210906,HS-grad,9,Married-civ-spouse,Exec-managerial,Other-relative,White,Female,0,0,40,United-States,<=50K
18591,28,NaN,389857,HS-grad,9,Married-civ-spouse,NaN,Other-relative,White,Male,0,0,16,United-States,<=50K
18660,23,Private,148709,HS-grad,9,Married-civ-spouse,Adm-clerical,Other-relative,White,Female,0,0,35,United-States,<=50K
18747,23,Private,80680,Some-college,10,Married-civ-spouse,Sales,Own-child,White,Female,0,0,16,United-States,<=50K
18760,30,Federal-gov,76313,HS-grad,9,Married-civ-spouse,Armed-Forces,Other-relative,Amer-Indian-Eskimo,Male,0,0,48,United-States,<=50K
18791,17,Private,186890,10th,6,Married-civ-spouse,Sales,Own-child,White,Female,0,0,30,United-States,<=50K
18926,43,Self-emp-inc,150533,Assoc-voc,11,Married-civ-spouse,Exec-managerial,Other-relative,White,Male,0,0,50,United-States,>50K
19008,33,Self-emp-not-inc,102884,Bachelors,13,Married-civ-spouse,Sales,Own-child,White,Male,0,0,20,United-States,<=50K
19061,51,Private,360131,5th-6th,3,Married-civ-spouse,Craft-repair,Other-relative,White,Female,0,0,40,United-States,<=50K
19755,22,NaN,228480,HS-grad,9,Married-civ-spouse,NaN,Own-child,White,Female,0,0,20,United-States,<=50K
19863,51,Private,70767,HS-grad,9,Married-civ-spouse,Adm-clerical,Other-relative,White,Female,0,0,40,United-States,<=50K
19962,27,Private,144133,Bachelors,13,Married-civ-spouse,Exec-managerial,Other-relative,White,Male,0,0,50,United-States,<=50K
20411,35,Self-emp-not-inc,112497,HS-grad,9,Married-civ-spouse,Craft-repair,Other-relative,White,Male,0,0,35,Ireland,<=50K
20510,28,Private,189241,11th,7,Married-civ-spouse,Handlers-cleaners,Own-child,White,Male,0,0,40,United-States,<=50K
20529,44,Local-gov,262241,HS-grad,9,Married-civ-spouse,Adm-clerical,Other-relative,White,Female,0,0,40,United-States,<=50K
20571,31,State-gov,59969,HS-grad,9,Married-civ-spouse,Adm-clerical,Other-relative,White,Female,0,0,35,United-States,<=50K
20694,36,Private,183739,HS-grad,9,Married-civ-spouse,Craft-repair,Own-child,White,Female,0,2002,40,United-States,<=50K
20894,23,Private,211160,12th,8,Married-civ-spouse,Handlers-cleaners,Own-child,White,Male,0,0,40,United-States,<=50K
20931,25,Private,469697,Some-college,10,Married-civ-spouse,Craft-repair,Own-child,White,Male,0,0,40,United-States,<=50K
20987,29,Self-emp-not-inc,104423,Some-college,10,Married-civ-spouse,Exec-managerial,Other-relative,White,Male,4386,0,45,United-States,>50K
21039,24,Private,52028,1st-4th,2,Married-civ-spouse,Other-service,Own-child,Asian-Pac-Islander,Female,0,0,5,Vietnam,<=50K
21076,27,Private,214858,HS-grad,9,Married-civ-spouse,Other-service,Own-child,White,Male,0,0,40,United-States,<=50K
21214,46,Self-emp-not-inc,176319,HS-grad,9,Married-civ-spouse,Sales,Own-child,White,Female,7298,0,40,United-States,>50K
21428,30,Private,60426,HS-grad,9,Married-civ-spouse,Adm-clerical,Own-child,Amer-Indian-Eskimo,Female,0,0,40,United-States,<=50K
21445,24,NaN,256240,7th-8th,4,Married-civ-spouse,NaN,Own-child,White,Male,0,0,60,United-States,<=50K
21661,55,Private,76860,HS-grad,9,Married-civ-spouse,Other-service,Other-relative,Asian-Pac-Islander,Male,0,0,40,Philippines,<=50K
21789,30,Local-gov,115040,HS-grad,9,Married-civ-spouse,Handlers-cleaners,Other-relative,White,Male,0,0,25,United-States,<=50K
21885,25,Private,195481,HS-grad,9,Married-civ-spouse,Adm-clerical,Other-relative,White,Male,0,0,40,United-States,<=50K
21894,23,Self-emp-not-inc,409230,1st-4th,2,Married-civ-spouse,Sales,Other-relative,White,Male,0,0,40,United-States,<=50K
21910,26,Private,421561,11th,7,Married-civ-spouse,Other-service,Other-relative,White,Male,0,0,25,United-States,<=50K
22076,31,Private,193215,Some-college,10,Married-civ-spouse,Exec-managerial,Own-child,White,Male,0,0,50,United-States,<=50K
22133,36,Private,112497,9th,5,Married-civ-spouse,Sales,Own-child,White,Male,0,0,50,United-States,>50K
22346,20,Private,470875,HS-grad,9,Married-civ-spouse,Sales,Own-child,Black,Male,0,0,32,United-States,<=50K
22637,32,Private,288229,Some-college,10,Married-civ-spouse,Sales,Other-relative,Asian-Pac-Islander,Female,0,0,40,Greece,<=50K
22895,19,NaN,200790,12th,8,Married-civ-spouse,NaN,Other-relative,White,Female,15024,0,40,United-States,>50K
23331,29,Private,144808,Some-college,10,Married-civ-spouse,Exec-managerial,Own-child,Black,Female,0,0,40,United-States,<=50K
23352,28,Private,194472,Some-college,10,Married-civ-spouse,Adm-clerical,Own-child,White,Female,0,0,40,United-States,<=50K
23383,66,Private,28367,Bachelors,13,Married-civ-spouse,Priv-house-serv,Other-relative,White,Male,0,0,99,United-States,<=50K
23581,24,Private,282604,Some-college,10,Married-civ-spouse,Protective-serv,Other-relative,White,Male,0,0,24,United-States,<=50K
23592,58,Private,119751,HS-grad,9,Married-civ-spouse,Priv-house-serv,Other-relative,Asian-Pac-Islander,Female,0,0,60,Philippines,<=50K
23674,43,Self-emp-inc,82488,Bachelors,13,Married-civ-spouse,Sales,Own-child,Asian-Pac-Islander,Female,0,0,40,Philippines,>50K
23812,27,Private,381789,12th,8,Married-civ-spouse,Farming-fishing,Own-child,White,Male,0,0,55,United-States,<=50K
23860,19,Private,316797,7th-8th,4,Married-civ-spouse,Handlers-cleaners,Own-child,White,Male,0,0,45,Mexico,<=50K
24053,30,Private,345705,Some-college,10,Married-civ-spouse,Exec-managerial,Other-relative,White,Male,0,0,40,United-States,<=50K
24118,35,NaN,333305,Some-college,10,Married-civ-spouse,NaN,Own-child,White,Female,0,0,40,United-States,<=50K
24540,34,Private,137088,HS-grad,9,Married-civ-spouse,Craft-repair,Other-relative,Amer-Indian-Eskimo,Male,0,0,40,United-States,<=50K
24564,35,NaN,226379,HS-grad,9,Married-civ-spouse,NaN,Other-relative,White,Female,0,0,25,United-States,<=50K
24793,33,Private,238002,9th,5,Married-civ-spouse,Transport-moving,Other-relative,White,Male,0,0,40,Mexico,<=50K
24800,50,Private,23686,Some-college,10,Married-civ-spouse,Adm-clerical,Other-relative,White,Female,0,0,35,United-States,>50K

In [12]:
df['workclass'].value_counts()

workclass
Private             33860
Self-emp-not-inc     3861
Local-gov            3136
State-gov            1981
Self-emp-inc         1694
Federal-gov          1432
Without-pay            21
Never-worked           10
Name: count, dtype: int64

In [28]:
df['fnlwgt'].value_counts()

fnlwgt
203488    21
190290    19
120277    19
125892    18
126569    18
          ..
269623     1
224655     1
173449     1
89686      1
350977     1
Name: count, Length: 28523, dtype: int64

In [19]:
df['marital_status'].value_counts()

marital_status
Married-civ-spouse       22366
Never-married            16082
Divorced                  6630
Separated                 1530
Widowed                   1518
Married-spouse-absent      627
Married-AF-spouse           37
Name: count, dtype: int64

In [20]:
df['occupation'].value_counts()

occupation
Prof-specialty       6165
Craft-repair         6102
Exec-managerial      6082
Adm-clerical         5606
Sales                5501
Other-service        4919
Machine-op-inspct    3017
Transport-moving     2355
Handlers-cleaners    2071
Farming-fishing      1485
Tech-support         1445
Protective-serv       982
Priv-house-serv       240
Armed-Forces           15
Name: count, dtype: int64

In [21]:
df['relationship'].value_counts()

relationship
Husband           19703
Not-in-family     12557
Own-child          7569
Unmarried          5124
Wife               2331
Other-relative     1506
Name: count, dtype: int64

In [22]:
df['race'].value_counts()

race
White                 41714
Black                  4683
Asian-Pac-Islander     1517
Amer-Indian-Eskimo      470
Other                   406
Name: count, dtype: int64

In [23]:
df['sex'].value_counts()

sex
Male      32614
Female    16176
Name: count, dtype: int64

In [24]:
df['native_country'].value_counts()

native_country
United-States                 43792
Mexico                          943
Philippines                     294
Germany                         206
Puerto-Rico                     184
Canada                          182
El-Salvador                     155
India                           151
Cuba                            138
England                         127
China                           122
South                           115
Jamaica                         106
Italy                           105
Dominican-Republic              103
Japan                            92
Poland                           87
Guatemala                        86
Vietnam                          86
Columbia                         85
Haiti                            75
Portugal                         67
Taiwan                           65
Iran                             59
Greece                           49
Nicaragua                        49
Peru                             46
Ecuador                          45
France                           38
Ireland                          37
Hong                             30
Thailand                         30
Cambodia                         28
Trinadad&Tobago                  27
Laos                             23
Outlying-US(Guam-USVI-etc)       23
Yugoslavia                       23
Scotland                         21
Honduras                         20
Hungary                          19
Holand-Netherlands                1
Name: count, dtype: int64

In [25]:
df['class'].value_counts()

class
<=50K    37109
>50K     11681
Name: count, dtype: int64

In [29]:
df['education_num'].value_counts()

education_num
9     15770
10    10863
13     8013
14     2656
11     2060
7      1812
12     1601
6      1389
4       954
15      834
5       756
8       655
16      594
3       507
2       245
1        81
Name: count, dtype: int64