In [2]:
from src.main import data 
import pandas as pd

data
df = data.frame
df

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,class
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48785,39,Private,215419,Bachelors,13,Divorced,Prof-specialty,Not-in-family,White,Female,0,0,36,United-States,<=50K
48786,64,NaN,321403,HS-grad,9,Widowed,NaN,Other-relative,Black,Male,0,0,40,United-States,<=50K
48787,38,Private,374983,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,50,United-States,<=50K
48788,44,Private,83891,Bachelors,13,Divorced,Adm-clerical,Own-child,Asian-Pac-Islander,Male,5455,0,40,United-States,<=50K
48789,35,Self-emp-inc,182148,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,60,United-States,>50K

In [3]:
df.info()
df.isna().sum()
df.duplicated().sum()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 48790 entries, 0 to 48789
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             48790 non-null  int64
 1   workclass       45995 non-null  category
 2   fnlwgt          48790 non-null  int64
 3   education       48790 non-null  category
 4   education_num   48790 non-null  int64
 5   marital_status  48790 non-null  category
 6   occupation      45985 non-null  category
 7   relationship    48790 non-null  category
 8   race            48790 non-null  category
 9   sex             48790 non-null  category
 10  capital_gain    48790 non-null  int64
 11  capital_loss    48790 non-null  int64
 12  hours_per_week  48790 non-null  int64
 13  native_country  47934 non-null  category
 14  class           48790 non-null  category
dtypes: category(9), int64(6)
memory usage: 2.7 MB

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week
count,48790.000000,4.879000e+04,48790.000000,48790.000000,48790.000000,48790.000000
mean,38.652798,1.896690e+05,10.078807,1080.217688,87.595573,40.425886
std,13.708493,1.056172e+05,2.570046,7455.905921,403.209129,12.392729
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.175550e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.781385e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.376062e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.490400e+06,16.000000,99999.000000,4356.000000,99.000000

In [29]:
pd.set_option('display.max_rows', 500)
df.sort_values(['education_num'], ascending= True)
print(len(df[df['education_num'] == 1]))
print(len(df[df['education_num'] == 2]))
print(len(df[df['education_num'] == 3]))
print(len(df[df['education_num'] == 4]))
df[df['education_num'] == 3].head(15)

81
245
507
954

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,class
56,46,Private,216666,5th-6th,3,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,Mexico,<=50K
195,23,Private,197387,5th-6th,3,Married-civ-spouse,Transport-moving,Other-relative,White,Male,0,0,40,Mexico,<=50K
317,22,Private,399087,5th-6th,3,Married-civ-spouse,Machine-op-inspct,Other-relative,White,Female,0,0,40,Mexico,<=50K
335,17,Private,270942,5th-6th,3,Never-married,Other-service,Other-relative,White,Male,0,0,48,Mexico,<=50K
381,46,Private,214955,5th-6th,3,Divorced,Craft-repair,Not-in-family,White,Female,0,2339,45,United-States,<=50K
497,23,Private,403107,5th-6th,3,Never-married,Other-service,Own-child,White,Male,0,0,40,El-Salvador,<=50K
511,53,NaN,251804,5th-6th,3,Widowed,NaN,Unmarried,Black,Female,0,0,30,United-States,<=50K
638,47,Self-emp-inc,248145,5th-6th,3,Married-civ-spouse,Transport-moving,Husband,White,Male,0,0,50,Cuba,<=50K
771,37,Private,327323,5th-6th,3,Separated,Farming-fishing,Not-in-family,White,Male,0,0,32,Guatemala,<=50K
874,55,Private,282753,5th-6th,3,Divorced,Other-service,Unmarried,Black,Male,0,0,25,United-States,<=50K
922,42,Private,274198,5th-6th,3,Married-civ-spouse,Machine-op-inspct,Wife,White,Female,0,0,38,Mexico,<=50K
1295,26,Private,280093,5th-6th,3,Married-civ-spouse,Craft-repair,Husband,White,Male,0,1628,50,United-States,<=50K
1307,26,Private,202203,5th-6th,3,Never-married,Adm-clerical,Own-child,White,Female,0,0,40,Mexico,<=50K
1354,58,Private,132606,5th-6th,3,Divorced,Machine-op-inspct,Not-in-family,Black,Male,0,0,40,United-States,<=50K
1544,69,NaN,473040,5th-6th,3,Divorced,NaN,Not-in-family,White,Male,0,0,40,United-States,<=50K

In [ ]:
pd.set_option('display.max_rows', 250)

df2 = df[df['marital_status'] == 'Never-married']
df2['relationship'].value_counts()
# correspondance ok entre 'never married' et relationship

df3 = df[df['marital_status'] == 'Married-civ-spouse']
df3['relationship'].value_counts()
df3[(df3['relationship']=='Own-child') | (df3['relationship']=='Other-relative')].head(250)
# outliers entre married-civ-spoused et own-child(143)
df3 = df3[df3['relationship'] != 'Own-child']


df4 = df[df['marital_status'] == 'Married-spouse-absent']
df4['relationship'].value_counts()
# outliers eavec 'unmarried'(183) et 'ownchild'(61)
df4 = df4[~df4['relationship'].isin(['Own-child', 'Unmarried'])]


df5 = df[df['marital_status'] == 'Separated']
df5['relationship'].value_counts()
# outliers avec 'ownchild'(145)potentiellement à passer en other-relative
df5 = df5[df5['relationship'] != 'Own-child']


df6 = df[df['marital_status'] == 'Divorced']
df6['relationship'].value_counts()
# outliers 'own-child"(455)
#Si une personne a été mariée par le passé (Divorcée, Séparée, Veuve) 
# mais qu'elle est étiquetée Own-child, on la bascule en Other-relative
df6 = df6[df6['relationship'] != 'Own-child']


df7 = df[df['marital_status'] == 'Widowed']
df7['relationship'].value_counts()
# outliers 'own-child"(25)
df7 = df7[df7['relationship'] != 'Own-child']

df7
# environ mille lignes supprimées 
df_drop = pd.concat([df2,df3,df4,df5,df6,df7], ignore_index= True)
df_drop

<class 'pandas.DataFrame'>
RangeIndex: 47740 entries, 0 to 47739
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             47740 non-null  int64
 1   workclass       45025 non-null  category
 2   fnlwgt          47740 non-null  int64
 3   education       47740 non-null  category
 4   education_num   47740 non-null  int64
 5   marital_status  47740 non-null  category
 6   occupation      45015 non-null  category
 7   relationship    47740 non-null  category
 8   race            47740 non-null  category
 9   sex             47740 non-null  category
 10  capital_gain    47740 non-null  int64
 11  capital_loss    47740 non-null  int64
 12  hours_per_week  47740 non-null  int64
 13  native_country  46894 non-null  category
 14  class           47740 non-null  category
dtypes: category(9), int64(6)
memory usage: 2.6 MB

In [12]:
df['workclass'].value_counts()

workclass
Private             33860
Self-emp-not-inc     3861
Local-gov            3136
State-gov            1981
Self-emp-inc         1694
Federal-gov          1432
Without-pay            21
Never-worked           10
Name: count, dtype: int64

In [ ]:
df['fnlwgt'].value_counts()

In [ ]:
df['marital_status'].value_counts()

In [ ]:
df['occupation'].value_counts()

In [ ]:
df['relationship'].value_counts()

In [ ]:
df['race'].value_counts()

In [ ]:
df['sex'].value_counts()

In [ ]:
df['native_country'].value_counts()

In [25]:
df['class'].value_counts()

class
<=50K    37109
>50K     11681
Name: count, dtype: int64

In [ ]:
df['education_num'].value_counts()

In [40]:
pd.set_option('display.max_rows', 250)
df_drop[
    (df_drop['occupation'].isna()) | 
    (df_drop['workclass'].isna()) | 
    (df_drop['native_country'].isna())
].head(30)

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,class
13,18,Private,226956,HS-grad,9,Never-married,Other-service,Own-child,White,Female,0,0,30,NaN,<=50K
14,25,NaN,200681,Some-college,10,Never-married,NaN,Own-child,White,Male,0,0,40,United-States,<=50K
27,17,NaN,304873,10th,6,Never-married,NaN,Own-child,White,Female,34095,0,32,United-States,<=50K
62,19,NaN,170653,HS-grad,9,Never-married,NaN,Own-child,White,Male,0,0,40,Italy,<=50K
76,20,NaN,119156,Some-college,10,Never-married,NaN,Own-child,White,Male,0,0,20,United-States,<=50K
82,19,NaN,218956,Some-college,10,Never-married,NaN,Own-child,White,Male,0,0,24,Canada,<=50K
99,19,NaN,860348,Some-college,10,Never-married,NaN,Own-child,Black,Female,0,0,25,United-States,<=50K
104,23,NaN,211601,Assoc-voc,11,Never-married,NaN,Own-child,Black,Female,0,0,15,United-States,<=50K
129,20,NaN,137300,HS-grad,9,Never-married,NaN,Other-relative,White,Female,0,0,35,United-States,<=50K
138,17,NaN,202521,11th,7,Never-married,NaN,Own-child,White,Male,0,0,40,United-States,<=50K
146,17,NaN,258872,11th,7,Never-married,NaN,Own-child,White,Female,0,0,5,United-States,<=50K
151,22,NaN,139883,Some-college,10,Never-married,NaN,Own-child,White,Male,0,0,40,United-States,<=50K
160,52,NaN,271749,12th,8,Never-married,NaN,Other-relative,Black,Male,594,0,40,United-States,<=50K
173,20,NaN,214635,Some-college,10,Never-married,NaN,Own-child,White,Male,0,0,24,United-States,<=50K
174,21,NaN,204226,Some-college,10,Never-married,NaN,Unmarried,White,Female,0,0,35,United-States,<=50K
177,34,NaN,190027,HS-grad,9,Never-married,NaN,Unmarried,Black,Female,0,0,40,United-States,<=50K
191,18,NaN,165532,12th,8,Never-married,NaN,Own-child,White,Male,0,0,25,United-States,<=50K
200,23,NaN,99399,Some-college,10,Never-married,NaN,Unmarried,Amer-Indian-Eskimo,Female,0,0,25,United-States,<=50K
228,17,NaN,80077,11th,7,Never-married,NaN,Own-child,White,Female,0,0,20,United-States,<=50K
235,66,NaN,149422,7th-8th,4,Never-married,NaN,Not-in-family,White,Male,0,0,4,United-States,<=50K
241,25,NaN,202480,Assoc-acdm,12,Never-married,NaN,Other-relative,White,Male,0,0,45,United-States,<=50K
253,43,Private,177937,Bachelors,13,Never-married,Prof-specialty,Not-in-family,White,Male,0,0,40,NaN,>50K
279,21,NaN,149704,HS-grad,9,Never-married,NaN,Not-in-family,White,Female,1055,0,40,United-States,<=50K
280,18,NaN,196061,Some-college,10,Never-married,NaN,Own-child,White,Male,0,0,33,United-States,<=50K
289,22,NaN,219941,Some-college,10,Never-married,NaN,Own-child,Black,Male,0,0,40,United-States,<=50K
327,19,NaN,52114,Some-college,10,Never-married,NaN,Own-child,White,Female,0,0,10,United-States,<=50K
339,23,NaN,184699,HS-grad,9,Never-married,NaN,Unmarried,Black,Female,0,0,40,United-States,<=50K
348,19,NaN,117201,HS-grad,9,Never-married,NaN,Own-child,White,Male,0,0,30,United-States,<=50K
351,30,Private,201624,Bachelors,13,Never-married,Prof-specialty,Not-in-family,Black,Male,0,0,45,NaN,<=50K
356,19,NaN,241616,HS-grad,9,Never-married,NaN,Unmarried,White,Male,0,2001,40,United-States,<=50K

In [39]:
df_drop.isna().value_counts()

age    workclass  fnlwgt  education  education_num  marital_status  occupation  relationship  race   sex    capital_gain  capital_loss  hours_per_week  native_country  class
False  False      False   False      False          False           False       False         False  False  False         False         False           False           False    44213
       True       False   False      False          False           True        False         False  False  False         False         False           False           False     2671
       False      False   False      False          False           False       False         False  False  False         False         False           True            False      802
       True       False   False      False          False           True        False         False  False  False         False         False           True            False       44
       False      False   False      False          False           True        False         False  False  False         False         False           False           False       10
Name: count, dtype: int64

In [ ]:
# ajout des catégories unknown pour pallier aux NaN

df_drop[
    (df_drop['occupation'].isna()) &
    (df_drop['workclass'].isna())  
   ].head(30)


df_drop["workclass"] = df_drop["workclass"].fillna("Unknown")
df_drop["occupation"] = df_drop["occupation"].fillna("Unknown")
df_drop

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,class
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,31,Private,45781,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Female,14084,0,50,United-States,>50K
2,23,Private,122272,Bachelors,13,Never-married,Adm-clerical,Own-child,White,Female,0,0,30,United-States,<=50K
3,32,Private,205019,Assoc-acdm,12,Never-married,Sales,Not-in-family,Black,Male,0,0,50,United-States,<=50K
4,25,Self-emp-not-inc,176756,HS-grad,9,Never-married,Farming-fishing,Own-child,White,Male,0,0,35,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47735,56,State-gov,160383,10th,6,Widowed,Other-service,Not-in-family,White,Female,0,0,37,United-States,<=50K
47736,48,Private,236197,12th,8,Widowed,Handlers-cleaners,Not-in-family,Asian-Pac-Islander,Male,0,0,40,Guatemala,<=50K
47737,66,Private,344436,HS-grad,9,Widowed,Sales,Other-relative,White,Female,0,0,8,United-States,<=50K
47738,64,Self-emp-not-inc,136405,HS-grad,9,Widowed,Farming-fishing,Not-in-family,White,Male,0,0,32,United-States,<=50K
47739,64,Unknown,321403,HS-grad,9,Widowed,Unknown,Other-relative,Black,Male,0,0,40,United-States,<=50K

In [48]:
pd.set_option('display.max_rows', 250)
df_drop[df_drop['native_country'].isna()].head(50)

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,class
13,18,Private,226956,HS-grad,9,Never-married,Other-service,Own-child,White,Female,0,0,30,NaN,<=50K
253,43,Private,177937,Bachelors,13,Never-married,Prof-specialty,Not-in-family,White,Male,0,0,40,NaN,>50K
351,30,Private,201624,Bachelors,13,Never-married,Prof-specialty,Not-in-family,Black,Male,0,0,45,NaN,<=50K
386,24,Unknown,35633,Some-college,10,Never-married,Unknown,Not-in-family,White,Male,0,0,40,NaN,<=50K
387,26,Private,227332,Bachelors,13,Never-married,Transport-moving,Unmarried,Asian-Pac-Islander,Male,0,0,40,NaN,<=50K
509,41,Self-emp-not-inc,195124,HS-grad,9,Never-married,Sales,Not-in-family,White,Male,0,0,50,NaN,<=50K
522,31,Private,169104,Bachelors,13,Never-married,Sales,Own-child,Asian-Pac-Islander,Male,0,0,40,NaN,<=50K
615,29,Private,149943,Some-college,10,Never-married,Other-service,Not-in-family,Other,Male,0,1590,40,NaN,<=50K
645,19,Private,365640,HS-grad,9,Never-married,Priv-house-serv,Not-in-family,White,Female,0,0,45,NaN,<=50K
658,31,Private,170430,Prof-school,15,Never-married,Prof-specialty,Not-in-family,White,Female,0,0,80,NaN,<=50K
821,28,Private,173649,HS-grad,9,Never-married,Other-service,Own-child,Black,Female,0,0,40,NaN,<=50K
862,28,Private,128509,5th-6th,3,Never-married,Machine-op-inspct,Not-in-family,White,Female,0,0,40,NaN,<=50K
896,26,Private,225279,Some-college,10,Never-married,Prof-specialty,Not-in-family,White,Male,0,1602,40,NaN,<=50K
990,38,Private,53930,10th,6,Never-married,Craft-repair,Not-in-family,Black,Male,0,0,40,NaN,<=50K
1024,25,Unknown,237865,Some-college,10,Never-married,Unknown,Own-child,Black,Male,0,0,40,NaN,<=50K
1041,37,Private,325538,HS-grad,9,Never-married,Exec-managerial,Own-child,White,Male,0,0,60,NaN,<=50K
1126,42,Private,217826,HS-grad,9,Never-married,Craft-repair,Own-child,Black,Male,0,0,40,NaN,<=50K
1132,21,Private,182606,Some-college,10,Never-married,Other-service,Own-child,Black,Male,0,0,40,NaN,<=50K
1144,34,Private,127651,10th,6,Never-married,Farming-fishing,Not-in-family,White,Male,0,0,44,NaN,<=50K
1162,21,Unknown,180303,Bachelors,13,Never-married,Unknown,Not-in-family,Asian-Pac-Islander,Male,0,0,25,NaN,<=50K
1246,32,Unknown,169886,Bachelors,13,Never-married,Unknown,Not-in-family,White,Female,0,0,20,NaN,<=50K
1256,22,Private,129934,Some-college,10,Never-married,Adm-clerical,Not-in-family,Asian-Pac-Islander,Male,0,0,40,NaN,<=50K
1257,31,Private,375680,Bachelors,13,Never-married,Prof-specialty,Unmarried,Black,Female,0,0,40,NaN,<=50K
1297,35,Private,124483,Bachelors,13,Never-married,Sales,Not-in-family,Asian-Pac-Islander,Male,0,0,50,NaN,>50K
1351,20,Private,54152,Some-college,10,Never-married,Adm-clerical,Own-child,White,Female,0,0,30,NaN,<=50K
1410,25,Private,204338,HS-grad,9,Never-married,Farming-fishing,Unmarried,White,Male,0,0,30,NaN,<=50K
1442,17,Private,160118,12th,8,Never-married,Sales,Not-in-family,White,Female,0,0,10,NaN,<=50K
1529,30,Local-gov,125159,Bachelors,13,Never-married,Prof-specialty,Not-in-family,Black,Male,14084,0,45,NaN,>50K
1536,18,Private,146378,Some-college,10,Never-married,Other-service,Own-child,White,Female,0,0,40,NaN,<=50K
1585,24,Private,184400,HS-grad,9,Never-married,Transport-moving,Own-child,Asian-Pac-Islander,Male,0,0,30,NaN,<=50K
1681,37,Private,163392,HS-grad,9,Never-married,Transport-moving,Other-relative,Asian-Pac-Islander,Male,0,0,40,NaN,<=50K
1709,21,Private,206861,Some-college,10,Never-married,Sales,Own-child,White,Male,0,0,20,NaN,<=50K
1755,41,Private,70037,Some-college,10,Never-married,Craft-repair,Unmarried,White,Male,0,3004,60,NaN,>50K
1791,25,Private,233777,HS-grad,9,Never-married,Transport-moving,Other-relative,White,Male,0,0,40,NaN,<=50K
1805,21,Private,206492,HS-grad,9,Never-married,Sales,Own-child,White,Female,0,0,40,NaN,<=50K
1868,30,Private,164190,HS-grad,9,Never-married,Adm-clerical,Not-in-family,White,Male,0,0,38,NaN,<=50K
1972,36,Private,189674,HS-grad,9,Never-married,Priv-house-serv,Unmarried,Black,Female,0,0,28,NaN,<=50K
2052,27,Private,195681,Some-college,10,Never-married,Prof-specialty,Not-in-family,White,Female,0,0,48,NaN,<=50K
2097,42,Private,132633,HS-grad,9,Never-married,Priv-house-serv,Not-in-family,White,Female,0,0,40,NaN,<=50K
2098,33,Private,164707,Assoc-acdm,12,Never-married,Exec-managerial,Unmarried,White,Female,2174,0,55,NaN,<=50K
2105,30,Private,179112,Bachelors,13,Never-married,Prof-specialty,Own-child,Black,Male,0,0,40,NaN,<=50K
2111,24,Federal-gov,215115,Bachelors,13,Never-married,Tech-support,Own-child,White,Female,0,0,40,NaN,<=50K
2160,35,Private,188069,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Male,13550,0,55,NaN,>50K
2206,25,Private,310864,Bachelors,13,Never-married,Tech-support,Not-in-family,Black,Male,0,0,40,NaN,<=50K
2327,18,Private,74054,11th,7,Never-married,Sales,Own-child,Other,Female,0,0,20,NaN,<=50K
2353,20,Private,197496,Some-college,10,Never-married,Sales,Own-child,White,Male,0,0,30,NaN,<=50K
2402,40,Federal-gov,163215,Bachelors,13,Never-married,Prof-specialty,Not-in-family,White,Female,0,0,40,NaN,<=50K
2423,20,Private,285295,Some-college,10,Never-married,Machine-op-inspct,Not-in-family,Asian-Pac-Islander,Female,0,0,40,NaN,<=50K
2468,38,Private,193026,HS-grad,9,Never-married,Other-service,Unmarried,White,Male,0,1408,40,NaN,<=50K
2584,29,Unknown,125159,Some-college,10,Never-married,Unknown,Not-in-family,Black,Male,0,0,36,NaN,<=50K

In [54]:
# proportion des classes pouir les lignes où native country n'est pas renseigné
df[df["native_country"].isna()]["class"].value_counts(normalize=True)

# supression des lignes
df_drop = df_drop.dropna(subset=["native_country"])
df_drop = df_drop.reset_index(drop=True)
df_drop.info()
df_drop

<class 'pandas.DataFrame'>
RangeIndex: 46894 entries, 0 to 46893
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             46894 non-null  int64
 1   workclass       46894 non-null  category
 2   fnlwgt          46894 non-null  int64
 3   education       46894 non-null  category
 4   education_num   46894 non-null  int64
 5   marital_status  46894 non-null  category
 6   occupation      46894 non-null  category
 7   relationship    46894 non-null  category
 8   race            46894 non-null  category
 9   sex             46894 non-null  category
 10  capital_gain    46894 non-null  int64
 11  capital_loss    46894 non-null  int64
 12  hours_per_week  46894 non-null  int64
 13  native_country  46894 non-null  category
 14  class           46894 non-null  category
dtypes: category(9), int64(6)
memory usage: 2.6 MB

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,class
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,31,Private,45781,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Female,14084,0,50,United-States,>50K
2,23,Private,122272,Bachelors,13,Never-married,Adm-clerical,Own-child,White,Female,0,0,30,United-States,<=50K
3,32,Private,205019,Assoc-acdm,12,Never-married,Sales,Not-in-family,Black,Male,0,0,50,United-States,<=50K
4,25,Self-emp-not-inc,176756,HS-grad,9,Never-married,Farming-fishing,Own-child,White,Male,0,0,35,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46889,56,State-gov,160383,10th,6,Widowed,Other-service,Not-in-family,White,Female,0,0,37,United-States,<=50K
46890,48,Private,236197,12th,8,Widowed,Handlers-cleaners,Not-in-family,Asian-Pac-Islander,Male,0,0,40,Guatemala,<=50K
46891,66,Private,344436,HS-grad,9,Widowed,Sales,Other-relative,White,Female,0,0,8,United-States,<=50K
46892,64,Self-emp-not-inc,136405,HS-grad,9,Widowed,Farming-fishing,Not-in-family,White,Male,0,0,32,United-States,<=50K
46893,64,Unknown,321403,HS-grad,9,Widowed,Unknown,Other-relative,Black,Male,0,0,40,United-States,<=50K